### ISSUE TITLE
Kodi 19 python version 2.25.0 could not be satisfied

### ISSUE THREAD

**Issue by Crash82** [robbforce/script.playnite.launcher#1]
Every time I try to install Playnite Script In Kodi 19 it comes with this error "python version 2.25.0 could not be satisfied"

**Comment by robbforce** [comment]
I didn't know if anyone was using this. I've been reviewing the Kodi v19 add-on changes and started updating. It may take a little while to get this working again.

**Comment by Crash82** [comment]
Thank you for looking ind to it. I do not know how many people use it, but I have been happy with it for some time now as it is simple to use playnite to control all launches

Keep up the good work and take the time it takes to update it

**Comment by robbforce** [comment]
Forgot to comment on this. I did update the scripts to uplift to python3 and then did a good amount of refactoring to the main script. The primary intake fan on my HTPC has failed though, so I've been unable to unit test the changes. I have parts coming in next week to redo all the cooling, so I'll get back to this uplift once that's working again.

**Comment by Crash82** [comment]
Looking forward to seeing what you have done, but take it easy and do not stress over it… I am just glad you will update it and continue the good work.

**Comment by robbforce** [comment]
Closed with v1.1.0 release.
