### ISSUE TITLE
doesnt open 

### ISSUE THREAD

**Issue by OtakUma420** [robbforce/script.playnite.launcher#3]
i tried to launch it i dont know what im doing wrong but it just wont launch, i thought maybe it was set to the wrong path but Kodi doest see the %appdata% folder by default so i cant reassign a new path, i followed the guide and red the readme file but it doesnt help

**Comment by robbforce** [comment]
Uninstall that version and try installing this repo: https://github.com/robbforce/kodi.repo.robbforce
Then you can install a newer version of the add-on I built earlier this year. It was a big update, that worked for me, but I didn't get feedback that it worked for others, so left it silently released through the repo only. Let me know if it works for you.

As far as the paths, where are your Kodi and Playnite exes installed at? Those paths need to be in the config.

**Comment by robbforce** [comment]
Closing after no response.
